### ISSUE TITLE
Guard against cyclic structures in bridge.js

### ISSUE THREAD

**Issue by alexstrat** [kmiyashiro/grunt-mocha#100]
It can happens that mocha pass cyclic structures as argument of emitted event. In `bridge.js` that makes the [JSON.stringify](https://github.com/kmiyashiro/grunt-mocha/blob/master/phantomjs/bridge.js#L16) fails in a non trivial error:

```
 1) BlablaEditView #render should have select2 inputs:
     TypeError: JSON.stringify cannot serialize cyclic structures.
      at sendMessage (/Users/alex/Work4Labs/work4us/node_modules/grunt-mocha/phantomjs/bridge.js:16)
      at /Users/alex/Work4Labs/work4us/node_modules/grunt-mocha/phantomjs/bridge.js:32
      at http://127.0.0.1:9999/javascripts/test/libs/mocha.js:521
      at http://127.0.0.1:9999/javascripts/test/libs/mocha.js:4330
      at http://127.0.0.1:9999/javascripts/test/libs/mocha.js:4538
      at http://127.0.0.1:9999/javascripts/test/libs/mocha.js:4123
      ...
      ...
``` 

On my side I can reproduce by doing assertions (with Chai) on jquery objects:

```js
expect($('.foo')).to.have.length(2)
```

We should probably male the serialization safe to cyclic structures:
http://stackoverflow.com/questions/9382167/serializing-object-that-contains-cyclic-object-value

**Comment by alexanderdickson** [comment]
+1

**Comment by coquin** [comment]
Any progress on this issue? I tried to checkout `guard-cyclical` branch but my tests didn't work at all (I saw `SyntaxError: Parse error` without any info what actually got wrong).

**Comment by sophietk** [comment]
Hi, I think the parse error is due to a missing opening brace : https://github.com/kmiyashiro/grunt-mocha/commit/605a26963721124fc11d4fa14cace2fab1458851#diff-e13c31b37d59ab82c83534ae6bbadd2eR97

Without the typo, that fixes the initial problem of cyclic references.

**Comment by kmiyashiro** [comment]
@sophietk doh, that's what I get for not linting. If you already have one, could you give me a small test case for this issue?

**Comment by sophietk** [comment]
@kmiyashiro, here is an example:
```js
describe('AssertionError', function() {

    it('should fail with explicit message', function() {
        var luke = { name: 'Luke' };
        expect(luke).property('mother', 'Padmé');
    });

    it('should fail with explicit message, even if cyclic structures', function() {
        var luke = { name: 'Luke' },
            leia = { name: 'Leia' };
        luke.sister = leia;
        leia.brother = luke;
        expect(luke).property('mother', 'Padmé');
    });

});
```
The first test fails with an explicit assertion error: `expected { name: 'Luke' } to have a property 'mother'`
The second one fails with a TypeError exception: `TypeError: JSON.stringify cannot serialize cyclic structures.`
