### ISSUE TITLE
JSON reporter not working, dest file not in JSON

### ISSUE THREAD

**Issue by ain** [kmiyashiro/grunt-mocha#115]
Following task definition is not working:
``` javascript
mocha: {
  all: {
	options: {
	  run: true
	},
	src: ['test/index.html'],
	reporter: 'JSON',
	dest: 'test/mocha.json'
  }
}
```
JSON reporter is not considered, destination file does not feature JSON.

JSON is important for us as Bamboo expects it.

**Comment by kmiyashiro** [comment]
Discussion continued in #145, basically we need to capture stdout, which is problematic when running async tasks with grunt.
