### ISSUE TITLE
Ability to pass TZ parameter to Phantom

### ISSUE THREAD

**Issue by HamletDRC** [kmiyashiro/grunt-mocha#142]
I'd like to force a particular timezone for my unit tests. 

You can do this from the command line like this: 

    TZ=Europe/Berlin phantomjs script.js

See: https://stackoverflow.com/questions/21702903/phantomjs-set-browser-timezone-setting

Is there any way to do this in grunt-mocha? If not, can you add it please?

**Comment by kmiyashiro** [comment]
That's just setting the environment variable for the command and not specific to grunt-mocha or phantom.js.

http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
