### ISSUE TITLE
option for mocha-clean

### ISSUE THREAD

**Issue by ain** [kmiyashiro/grunt-mocha#147]
Would be good to have an option for [mocha-clean](https://github.com/rstacruz/mocha-clean).

Unless of course it's possible to use the latest Mocha version which pretty much obsoletes the `mocha-clean`.

**Comment by kmiyashiro** [comment]
have you tried implementing it in your html test runner? https://github.com/rstacruz/mocha-clean#usage-browser

**Comment by ain** [comment]
I'll test-run today and come back to you with some results, thanks!

**Comment by ain** [comment]
Unfortunately not working :(

**Comment by kmiyashiro** [comment]
The latest mocha should not break this runner, I'll look into bumping it.

**Comment by kmiyashiro** [comment]
I bumped mocha to latest in master.
