### ISSUE TITLE
how to change filepath for html_table_reporter in reporter options 

### ISSUE THREAD

**Issue by DeChrish** [kmiyashiro/grunt-mocha#148]
Mocha options :

config.mochaTest[name] = {
options: {
reporter: 'good-mocha-html-reporter',
timeout: 60000,
logErrors: true,
captureFile: directories.target + '/' + name + '/test-results.html'
}

good-mocha-html-reporter - config file:
module.exports = {
path: '', // full or relative path (relative to your execution folder)
filename: 'report.html',
mode: 'Verbose'
}

When i use 'good-mocha-html-reporter' in mocha options, the report is generated as 'report.html' which is added in reporter-config file.
I want to use captureFile option to save the report file.
Is it possible?

**Comment by kmiyashiro** [comment]
I think you meant to post to this project https://github.com/pghalliday/grunt-mocha-test
