### ISSUE TITLE
PhantomJS hangs around after tests

### ISSUE THREAD

**Issue by ryanshawty** [kmiyashiro/grunt-mocha#152]
Hi,

I've started to use grunt-mocha for running our test suite in phantomjs but currently having an issue where phantomjs hangs around after the mocha task has finished, the major issue is that it is using 100% CPU and slowing the build process down. What's even more worrying is that it doesn't even quit when grunt has finished.

**Comment by kmiyashiro** [comment]
Can you try it with a trivial test suite with a fresh install and see if it still happens on your machine? If not, it is likely something to do with your tests.

**Comment by kmiyashiro** [comment]
Closing since can't repro
