### ISSUE TITLE
Bump grunt-lib-phantomjs to ^1.0.0

### ISSUE THREAD

**Issue by wrumsby** [kmiyashiro/grunt-mocha#157]
This version brings in Phantom 2.1 which provides better support for ES5 features, including `Function.prototype.bind` which wasn't supported in Phantom 1.9.

**Comment by kmiyashiro** [comment]
Cool, this will go into the 1.0 release

**Comment by BYK** [comment]
Any news about this or the 1.0 release?

**Comment by kmiyashiro** [comment]
Hey guys, I have a branch for this here: https://github.com/kmiyashiro/grunt-mocha/tree/bump-phantom

Unfortunately, it's breaking the xunit file output test and I don't have time at the moment to investigate more. If anyone wants to investigate the cause, that would be a big help.

**Comment by BYK** [comment]
@kmiyashiro - thanks for the update! I'm willing to give a hand with this so I'll checkout the branch and see if I can fix it.

**Comment by td-edge** [comment]
+1

**Comment by BYK** [comment]
Okay, I got this working. I had to use latest master instead of the published `1.0.1` version of grunt-phantomjs since it had an important fix that prevented our tests from failing randomly.
