### ISSUE TITLE
Update to Latest Grunt please?

### ISSUE THREAD

**Issue by Darren-Mack** [kmiyashiro/grunt-mocha#162]
Can we have grunt-mocha updated to allow for Grunt 1.0.x as a peerDependency please?

**Comment by kmiyashiro** [comment]
Hi @Darren-Mack, you should be able to install Grunt 1.x as a peerDependency as of grunt-mocah 1.0.1 with this commit: https://github.com/kmiyashiro/grunt-mocha/commit/419dd106d883c95bb1252ab55110f756b0058437#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Please reopen if upgrading to 1.0.1 does not fix your issue.
