### ISSUE TITLE
Leaves phantomjs process running after done

### ISSUE THREAD

**Issue by arlobelshee** [kmiyashiro/grunt-mocha#33]
I'm running on Windows 7 with a tiny test suite.

The task works fine. It reports tests passing. However, when it finishes the phantomjs process does not exit. I discovered this after running tests a few hundred times, leaking around 8 GB of memory.

I attempted to debug. It appears that phantom-mocha-runner's sendMessage is not fully working as intended. In particular, the fs.write for the done message never returns. Thus, the done test branch never executes and phantom.exit() is not called.

Or, at least, that's the best that I could tell by inserting a bunch of sending of console messages.

This is not the whole problem. I moved the done check to be before the write and the proces still did not exit. I did, however, then see all the console messages.

**Comment by austing** [comment]
I've been getting this problem on Ubuntu 14.04 as well: phantomjs process taking 100% CPU, never closed.
It's related to a bug that has been fixed in grunt-lib-phantomjs since 0.4. Changing the package.json dependency from 0.4 to 0.7 solved my problem.
See this thread for the fix that has long since been merged into grunt-lib-phantomjs master: https://github.com/gruntjs/grunt-lib-phantomjs/pull/46

**Comment by kmiyashiro** [comment]
@austing can you check if grunt-lib-phantomjs 0.6 solves your issue? 0.7 has a bug https://github.com/gruntjs/grunt-lib-phantomjs/issues/78

**Comment by austing** [comment]
I get the same hanging process with grunt-lib-phantomjs 0.6. Only 0.7 fixes it! In fact I think that the changes that lead to redundantly killing phantomjs are the same ones that take care of the zombie process. Personally I prefer a meaningless error message to a zombie process taking 100% cpu for hours!
Incidentally I'm loading modules with AMD for my tests, and that might have something to do with why grunt-lib-phantomjs is having trouble cleaning up.
(Just in case someone else stumbles across this thread in the same situation)

But may as well close this issue anyway, as it's an issue in grunt-lib-phantomjs and not in grunt-mocha.

**Comment by gyandeeps** [comment]
Found the issue and the solution: https://github.com/gruntjs/grunt-lib-phantomjs/pull/83
