### ISSUE TITLE
How do I configure grunt-mocha to report global leaks?

### ISSUE THREAD

**Issue by trevora** [kmiyashiro/grunt-mocha#43]
I asked this question on [StackOverflow](http://stackoverflow.com/q/14308178/330531) but got no answers.

I'm trying to us grunt-mocha 0.1.7 with grunt 0.3.17 and mocha 1.8.1.  I have some intentional global leaks in my code.  When I use mocha through a browser, I see these leaks reported.  However, no leaks are reported when I run mocha via grunt.

I tried several grunt configuration variations similar to

    mocha: {
       all: {
         src: ['test/**/*.html'],
         options: {
           ignoreLeaks: false
        }
      }

based on information on the GitHub project page, samples I found on the web, and by looking through the source.  I also tried to compare the source to the "spec" test reporter in the mocha source to see if there was something obvious that suggested that it wouldn't work.  I didn't see anything, although I must admit I'm still fairly new to JavaScript so I may have missed something.

Could you provide guidance on how to properly configure grunt-mocha to report global leaks?  Browser testing is fine for now, but I'd like to ultimately use a continuous integration server.

Thanks in advance.

Trevor

**Comment by kmiyashiro** [comment]
Closing due to age, please reopen if this is still important.
