### ISSUE TITLE
Fatal error: listen EADDRNOTAVAIL on $ grunt

### ISSUE THREAD

**Issue by oskarrough** [kmiyashiro/grunt-mocha#47]
Hi, when I run the following commands with Yeoman 1.0 and Grunt 0.4

```
$ yo webapp
$ npm install
$ bower install
$ grunt
```

I get the following error:

```
Running "mocha:all" (mocha) task
Testing index.htmlFatal error: listen EADDRNOTAVAIL
```

Tried running the [mocha test](http://visionmedia.github.com/mocha/) separately which works fine. I'm guessing some of my system dependancies are wrong. Any ideas?

Is this related? http://stackoverflow.com/questions/6829563/nodejs-error-eaddrnotavail-cannot-assign-requested-address

**Comment by zhishaofei3** [comment]
module.exports = {
  server: {
    options: {
      port: 80,
      base: '.',
      //keepalive: true,
      livereload: 35729,
      hostname: '192.168.191.1'
    }
  }
};

192.168.191.1 is my computer ip adress

**Comment by gnganpath** [comment]
I found the error occur from Gruntfile.js IP change  process.

**Comment by nikejaycn** [comment]
Try to edit you hosts file.

add: `127.0.0.1 locahost`

**Comment by derek-adair** [comment]
I had this same problem, definitely a problem with your host file
